'use client'

import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, Ban, BarChart3, Database, HardDrive, RefreshCw, ShieldCheck, UserRoundCheck, Users } from 'lucide-react'
import { supabase } from '@/lib/supabase-browser'
import { DropzoneLoader } from '@/components/feedback/DropzoneLoader'

function bytes(value: number) { if (!value) return '0 MB'; const units = ['B', 'KB', 'MB', 'GB']; const index = Math.min(Math.floor(Math.log(value) / Math.log(1024)), units.length - 1); return `${(value / 1024 ** index).toFixed(index > 1 ? 2 : 0)} ${units[index]}` }

export default function AdminPage() {
  const [data, setData] = useState<any>(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [tab, setTab] = useState<'overview'|'accounts'|'reports'|'audit'>('overview'), [search, setSearch] = useState('')
  async function headers() { const { data } = await supabase.auth.getSession(); if (!data.session) throw new Error('Entre com a conta administradora.'); return { Authorization: `Bearer ${data.session.access_token}`, 'Content-Type': 'application/json' } }
  async function load() { setLoading(true); setError(''); try { const res = await fetch('/api/admin/overview', { headers: await headers() }); const json = await res.json(); if (!res.ok) throw new Error(json.error); setData(json) } catch (err:any) { setError(err.message) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const accounts = useMemo(() => (data?.accounts || []).filter((item:any) => `${item.nome} ${item.username} ${item.tipo} ${item.status}`.toLowerCase().includes(search.toLowerCase())), [data, search])
  async function moderate(item:any, action:'suspender'|'banir'|'restaurar') { const reason = action === 'restaurar' ? 'Restrição removida pelo administrador.' : window.prompt(`Motivo para ${action} ${item.nome}:`); if (!reason) return; const days = action === 'suspender' ? Number(window.prompt('Quantidade de dias da suspensão:', '7') || 7) : null; const res = await fetch('/api/admin/moderation', { method:'PATCH', headers:await headers(), body:JSON.stringify({ action, target_type:item.tipo || 'campeonato', target_id:item.id, reason, days }) }); const json=await res.json(); if(!res.ok){setError(json.error);return} await load() }
  async function resolveReport(item:any, status:string) { const resolution = window.prompt('Informe a análise/resolução:', item.resolucao || ''); if (resolution === null) return; const res=await fetch('/api/admin/reports',{method:'PATCH',headers:await headers(),body:JSON.stringify({id:item.id,status,resolucao:resolution})});const json=await res.json();if(!res.ok){setError(json.error);return}await load() }
  if (loading && !data) return <DropzoneLoader label="Carregando administração" />
  const metrics = data?.metrics || {}, infra = metrics.infra || {}
  return <main className="system-admin-page">
    <header className="system-admin-header"><div><img src="/dropzone-icon.png" alt=""/><span><p>DropZone</p><h1>Administração do sistema</h1></span></div><button onClick={() => void load()}><RefreshCw size={16}/> Atualizar</button></header>
    <nav className="system-admin-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Visão geral</button><button className={tab==='accounts'?'active':''} onClick={()=>setTab('accounts')}>Contas</button><button className={tab==='reports'?'active':''} onClick={()=>setTab('reports')}>Denúncias <b>{metrics.reportsPending || 0}</b></button><button className={tab==='audit'?'active':''} onClick={()=>setTab('audit')}>Auditoria</button></nav>
    {error ? <div className="admin-feedback error">{error}</div> : null}
    {tab === 'overview' ? <><section className="admin-metric-grid"><article><Users/><span><strong>{metrics.authUsers || 0}</strong>Usuários autenticados</span></article><article><ShieldCheck/><span><strong>{metrics.profiles?.produtora || 0}</strong>Produtoras</span></article><article><ShieldCheck/><span><strong>{metrics.profiles?.equipe || 0}</strong>Equipes</span></article><article><UserRoundCheck/><span><strong>{metrics.profiles?.jogador || 0}</strong>Jogadores</span></article><article><UserRoundCheck/><span><strong>{metrics.profiles?.manager || 0}</strong>Managers</span></article><article><BarChart3/><span><strong>{metrics.championships || 0}</strong>Campeonatos</span></article><article><AlertTriangle/><span><strong>{metrics.reportsPending || 0}</strong>Denúncias abertas</span></article><article><Ban/><span><strong>{metrics.restrictions || 0}</strong>Restrições ativas</span></article></section><section className="admin-infra-grid"><article><Database/><div><small>Banco de dados</small><strong>{bytes(Number(infra.database_bytes || 0))}</strong></div></article><article><HardDrive/><div><small>Storage</small><strong>{bytes(Number(infra.storage_bytes || 0))}</strong><span>{infra.storage_objects || 0} arquivos</span></div></article></section></> : null}
    {tab === 'accounts' ? <section className="admin-section"><header><div><p>Moderação</p><h2>Contas e publicações</h2></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Pesquisar nome, usuário ou tipo"/></header><div className="admin-table-wrap"><table><thead><tr><th>Cadastro</th><th>Tipo</th><th>Status</th><th>Criado em</th><th>Ações</th></tr></thead><tbody>{accounts.map((item:any)=><tr key={`${item.tipo}-${item.id}`}><td><strong>{item.nome}</strong><small>@{item.username || '-'}</small></td><td>{item.tipo}</td><td><span className={`admin-status ${item.status}`}>{item.status}</span></td><td>{new Date(item.created_at).toLocaleDateString('pt-BR')}</td><td><div className="admin-row-actions">{item.status !== 'ativo' ? <button onClick={()=>void moderate(item,'restaurar')}>Restaurar</button> : <><button onClick={()=>void moderate(item,'suspender')}>Suspender</button><button className="danger" onClick={()=>void moderate(item,'banir')}>Banir</button></>}</div></td></tr>)}</tbody></table></div><h3>Campeonatos/publicações</h3><div className="admin-publication-grid">{(data?.championships||[]).map((item:any)=><article key={item.id}><div><strong>{item.nome}</strong><span className={`admin-status ${item.status}`}>{item.status}</span></div><div className="admin-row-actions">{item.status !== 'ativo'?<button onClick={()=>void moderate({...item,tipo:'campeonato'},'restaurar')}>Restaurar</button>:<><button onClick={()=>void moderate({...item,tipo:'campeonato'},'suspender')}>Suspender</button><button className="danger" onClick={()=>void moderate({...item,tipo:'campeonato'},'banir')}>Remover</button></>}</div></article>)}</div></section> : null}
    {tab === 'reports' ? <section className="admin-section"><header><div><p>Fila de análise</p><h2>Denúncias recebidas</h2></div></header><div className="admin-report-list">{(data?.reports||[]).map((item:any)=><article key={item.id}><header><span className={`admin-status ${item.status}`}>{item.status.replace('_',' ')}</span><time>{new Date(item.created_at).toLocaleString('pt-BR')}</time></header><strong>{item.categoria}</strong><p>{item.descricao}</p><small>{item.alvo_tipo} · {item.alvo_id}</small>{item.resolucao?<blockquote>{item.resolucao}</blockquote>:null}<div className="admin-row-actions"><button onClick={()=>void resolveReport(item,'em_analise')}>Analisar</button><button onClick={()=>void resolveReport(item,'resolvida')}>Resolver</button><button onClick={()=>void resolveReport(item,'arquivada')}>Arquivar</button></div></article>)}</div></section> : null}
    {tab === 'audit' ? <section className="admin-section"><header><div><p>Segurança</p><h2>Histórico administrativo</h2></div></header><div className="admin-audit-list">{(data?.audits||[]).map((item:any)=><div key={item.id}><strong>{item.acao.replaceAll('_',' ')}</strong><span>{item.alvo_tipo} · {item.alvo_id}</span><time>{new Date(item.created_at).toLocaleString('pt-BR')}</time></div>)}</div></section> : null}
  </main>
}
