'use client'

import { useState } from 'react'
import { Flag, X } from 'lucide-react'
import { supabase } from '@/lib/supabase-browser'
import { authHeaders } from '@/features/dropzone/utils'

export function ReportButton({ targetType, targetId, targetName }: { targetType: string; targetId: string; targetName: string }) {
  const [open, setOpen] = useState(false), [category, setCategory] = useState('conteudo_inadequado'), [description, setDescription] = useState(''), [message, setMessage] = useState(''), [loading, setLoading] = useState(false)
  async function submit() { setLoading(true); setMessage(''); try { const { data } = await supabase.auth.getSession(); if (!data.session) throw new Error('Entre na sua conta para enviar uma denúncia.'); const res = await fetch('/api/reports', { method:'POST', headers:{...authHeaders(data.session.access_token),'Content-Type':'application/json'}, body:JSON.stringify({ target_type:targetType, target_id:targetId, category, description }) }); const json=await res.json(); if(!res.ok) throw new Error(json.error); setMessage('Denúncia enviada para análise.'); setDescription('') } catch(err:any){setMessage(err.message)} finally{setLoading(false)} }
  return <><button className="directory-report-button" type="button" onClick={()=>setOpen(true)}><Flag size={14}/> Denunciar</button>{open?<div className="report-modal-backdrop" onClick={()=>setOpen(false)}><section className="report-modal" onClick={event=>event.stopPropagation()}><header><div><p className="eyebrow">Central de segurança</p><h2>Denunciar {targetName}</h2></div><button onClick={()=>setOpen(false)} aria-label="Fechar"><X size={18}/></button></header><label><span>Motivo</span><select value={category} onChange={event=>setCategory(event.target.value)}><option value="conteudo_inadequado">Conteúdo inadequado</option><option value="fraude">Fraude ou golpe</option><option value="assedio">Assédio</option><option value="identidade_falsa">Identidade falsa</option><option value="outro">Outro</option></select></label><label><span>Descrição</span><textarea value={description} onChange={event=>setDescription(event.target.value)} placeholder="Explique o que aconteceu e inclua informações que ajudem na análise."/></label>{message?<div className="admin-feedback">{message}</div>:null}<div className="button-row"><button className="button" onClick={()=>void submit()} disabled={loading||description.trim().length<10}>{loading?'Enviando...':'Enviar denúncia'}</button><button className="button secondary" onClick={()=>setOpen(false)}>Cancelar</button></div></section></div>:null}</>
}
