-- DropZone normalized schema.
-- Run this in Supabase SQL editor or through the Supabase CLI before deploying
-- code that reads campeonato_jogadores/jogadores_equipes.

create extension if not exists pgcrypto;

create or replace function public.dropzone_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.produtoras_perfis (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  public_id bigint generated by default as identity,
  public_id_prefix text default 'PD',
  username text not null,
  nome_exibido text not null,
  email_contato text not null,
  email_verificado boolean not null default false,
  logo_url text,
  pais text,
  estado text,
  cidade text,
  localidade text,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint produtoras_perfis_status_check check (status in ('ativo', 'pendente', 'bloqueado'))
);

create table if not exists public.equipes_perfis (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  public_id bigint generated by default as identity,
  public_id_prefix text default 'EQ',
  username text not null,
  nome_exibido text not null,
  email_contato text not null,
  email_verificado boolean not null default false,
  logo_url text,
  tag text not null,
  pais text,
  estado text,
  cidade text,
  localidade text,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint equipes_perfis_status_check check (status in ('ativo', 'pendente', 'bloqueado'))
);

create table if not exists public.jogadores_perfis (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  public_id bigint generated by default as identity,
  public_id_prefix text default 'JG',
  username text not null,
  nome_exibido text not null,
  email_contato text not null,
  email_verificado boolean not null default false,
  avatar_url text,
  id_jogo text not null,
  funcao text not null,
  pais text,
  estado text,
  cidade text,
  localidade text,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint jogadores_perfis_funcao_check check (funcao in ('support', 'rush', 'sniper', 'bomber')),
  constraint jogadores_perfis_status_check check (status in ('ativo', 'pendente', 'bloqueado'))
);

alter table public.jogadores_perfis add column if not exists public_id bigint generated by default as identity;
alter table public.jogadores_perfis add column if not exists public_id_prefix text default 'JG';

create table if not exists public.managers_perfis (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  public_id bigint generated by default as identity,
  public_id_prefix text default 'MN',
  username text not null,
  nome_exibido text not null,
  email_contato text not null,
  email_verificado boolean not null default false,
  avatar_url text,
  token_convite text,
  tipo_manager text,
  pais text,
  estado text,
  cidade text,
  localidade text,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint managers_perfis_status_check check (status in ('ativo', 'pendente', 'bloqueado'))
);

create table if not exists public.campeonatos (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  logo_url text,
  premiacao text,
  divisao_premiacao text,
  regras_url text,
  status text not null default 'ativo',
  criado_por uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.equipes (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  tag text not null,
  logo_url text,
  dono_auth_user_id uuid not null references auth.users(id) on delete cascade,
  senha_dono text,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.campeonato_equipes (
  id uuid primary key default gen_random_uuid(),
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  equipe_id uuid not null references public.equipes(id) on delete cascade,
  grupo_id uuid,
  slot_numero integer,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint campeonato_equipes_unique unique (campeonato_id, equipe_id)
);

create table if not exists public.campeonato_grupos (
  id uuid primary key default gen_random_uuid(),
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  nome text not null,
  slots integer not null default 12,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.campeonato_jogos (
  id uuid primary key default gen_random_uuid(),
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  nome text not null,
  data_jogo date,
  horario time,
  numero_partidas integer not null default 1,
  mapas text[] not null default '{}',
  grupos_ids uuid[] not null default '{}',
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.convites_tokens (
  id uuid primary key default gen_random_uuid(),
  token text not null unique,
  tipo text not null,
  tipo_acesso text,
  campeonato_id uuid references public.campeonatos(id) on delete cascade,
  equipe_id uuid references public.equipes(id) on delete cascade,
  jogo_id uuid references public.campeonato_jogos(id) on delete cascade,
  senha_hash text,
  criado_por uuid not null references auth.users(id) on delete cascade,
  usado boolean not null default false,
  usado_em timestamptz,
  expira_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint convites_tokens_tipo_check check (tipo in ('team_invite', 'player_invite', 'manager_invite'))
);

alter table public.convites_tokens add column if not exists tipo_acesso text;
alter table public.convites_tokens add column if not exists senha_hash text;
alter table public.convites_tokens drop constraint if exists convites_tokens_tipo_check;
alter table public.convites_tokens
  add constraint convites_tokens_tipo_check check (tipo in ('team_invite', 'player_invite', 'manager_invite'));

create table if not exists public.jogadores_equipes (
  id uuid primary key default gen_random_uuid(),
  jogador_auth_user_id uuid not null references auth.users(id) on delete cascade,
  equipe_id uuid not null references public.equipes(id) on delete cascade,
  origem text not null default 'manual',
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint jogadores_equipes_unique unique (jogador_auth_user_id, equipe_id)
);

do $$
begin
  if to_regclass('public.inscricoes_jogadores') is not null
     and to_regclass('public.campeonato_jogadores') is null then
    alter table public.inscricoes_jogadores rename to campeonato_jogadores;
  end if;
end $$;

create table if not exists public.campeonato_jogadores (
  id uuid primary key default gen_random_uuid(),
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  equipe_id uuid not null references public.equipes(id) on delete cascade,
  jogo_id uuid references public.campeonato_jogos(id) on delete set null,
  jogador_auth_user_id uuid not null references auth.users(id) on delete cascade,
  tag text,
  nick text not null,
  foto_url text,
  id_jogo text not null,
  funcao text not null,
  localidade text,
  senha text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint campeonato_jogadores_unique unique (campeonato_id, equipe_id, jogador_auth_user_id)
);

alter table public.campeonato_jogadores add column if not exists jogador_auth_user_id uuid references auth.users(id) on delete cascade;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'campeonato_equipes_grupo_fk'
  ) then
    alter table public.campeonato_equipes
      add constraint campeonato_equipes_grupo_fk
      foreign key (grupo_id) references public.campeonato_grupos(id) on delete set null
      not valid;
  end if;
end $$;

create unique index if not exists produtoras_perfis_username_idx on public.produtoras_perfis (lower(username));
create unique index if not exists equipes_perfis_username_idx on public.equipes_perfis (lower(username));
create unique index if not exists jogadores_perfis_username_idx on public.jogadores_perfis (lower(username));
create unique index if not exists managers_perfis_username_idx on public.managers_perfis (lower(username));
create unique index if not exists produtoras_perfis_public_id_idx on public.produtoras_perfis (public_id);
create unique index if not exists equipes_perfis_public_id_idx on public.equipes_perfis (public_id);
create unique index if not exists jogadores_perfis_public_id_idx on public.jogadores_perfis (public_id);
create unique index if not exists managers_perfis_public_id_idx on public.managers_perfis (public_id);
create unique index if not exists jogadores_perfis_id_jogo_idx on public.jogadores_perfis (id_jogo);
create index if not exists campeonatos_criado_por_idx on public.campeonatos (criado_por);
create index if not exists equipes_dono_auth_user_id_idx on public.equipes (dono_auth_user_id);
create index if not exists campeonato_equipes_campeonato_id_idx on public.campeonato_equipes (campeonato_id);
create index if not exists campeonato_equipes_equipe_id_idx on public.campeonato_equipes (equipe_id);
create index if not exists campeonato_jogadores_campeonato_id_idx on public.campeonato_jogadores (campeonato_id);
create index if not exists campeonato_jogadores_equipe_id_idx on public.campeonato_jogadores (equipe_id);
create index if not exists campeonato_jogadores_jogador_idx on public.campeonato_jogadores (jogador_auth_user_id);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'produtoras_perfis',
    'equipes_perfis',
    'jogadores_perfis',
    'managers_perfis',
    'campeonatos',
    'equipes',
    'campeonato_equipes',
    'campeonato_grupos',
    'campeonato_jogos',
    'convites_tokens',
    'jogadores_equipes',
    'campeonato_jogadores'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop trigger if exists trg_%I_updated_at on public.%I', table_name, table_name);
    execute format('create trigger trg_%I_updated_at before update on public.%I for each row execute function public.dropzone_set_updated_at()', table_name, table_name);
  end loop;
end $$;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant select on all tables in schema public to anon;

drop policy if exists "profiles read own produtora" on public.produtoras_perfis;
create policy "profiles read own produtora" on public.produtoras_perfis
for select to authenticated using ((select auth.uid()) = auth_user_id);

drop policy if exists "profiles read own equipe" on public.equipes_perfis;
create policy "profiles read own equipe" on public.equipes_perfis
for select to authenticated using ((select auth.uid()) = auth_user_id);

drop policy if exists "profiles read own jogador" on public.jogadores_perfis;
create policy "profiles read own jogador" on public.jogadores_perfis
for select to authenticated using ((select auth.uid()) = auth_user_id);

drop policy if exists "profiles read own manager" on public.managers_perfis;
create policy "profiles read own manager" on public.managers_perfis
for select to authenticated using ((select auth.uid()) = auth_user_id);

drop policy if exists "producer owns championships" on public.campeonatos;
create policy "producer owns championships" on public.campeonatos
for all to authenticated using ((select auth.uid()) = criado_por)
with check ((select auth.uid()) = criado_por);

drop policy if exists "team owner owns teams" on public.equipes;
create policy "team owner owns teams" on public.equipes
for all to authenticated using ((select auth.uid()) = dono_auth_user_id)
with check ((select auth.uid()) = dono_auth_user_id);

drop policy if exists "authenticated can read active championships" on public.campeonatos;
create policy "authenticated can read active championships" on public.campeonatos
for select to authenticated using (status = 'ativo');

drop policy if exists "authenticated can read active teams" on public.equipes;
create policy "authenticated can read active teams" on public.equipes
for select to authenticated using (status = 'ativo');

drop policy if exists "players read own championship entries" on public.campeonato_jogadores;
create policy "players read own championship entries" on public.campeonato_jogadores
for select to authenticated using ((select auth.uid()) = jogador_auth_user_id);

drop policy if exists "players insert own championship entries" on public.campeonato_jogadores;
create policy "players insert own championship entries" on public.campeonato_jogadores
for insert to authenticated with check ((select auth.uid()) = jogador_auth_user_id);
