import { expect, test } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const read = (file: string) => fs.readFileSync(path.join(root, file), 'utf8')

test.describe('Commerce — carrinho e favoritos persistidos', () => {
  test('banco, APIs, web e app ficam vinculados por usuário', async () => {
    const migration = read('database/migrations/20260808_commerce_cart_wishlist.sql')
    const cartApi = read('web/app/api/me/commerce/cart/route.ts')
    const checkoutApi = read('web/app/api/me/commerce/cart/checkout/route.ts')
    const wishlistApi = read('web/app/api/me/commerce/wishlist/route.ts')
    const webList = read('web/features/directory/components/DirectoryListClient.tsx')
    const cartPage = read('web/app/carrinho/page.tsx')
    const appApi = read('app/src/lib/api.ts')
    const appCommerce = read('app/src/lib/commerce.ts')
    const appVacancies = read('app/src/screens/VacanciesScreen.tsx')

    expect(migration).toContain('commerce_carrinhos')
    expect(migration).toContain('commerce_carrinho_itens')
    expect(migration).toContain('commerce_favoritos')
    expect(migration).toContain('enable row level security')
    expect(migration).toContain('auth.uid() = auth_user_id')
    expect(migration).toContain('references public.campeonatos')

    expect(cartApi).toContain('getBearerUser')
    expect(cartApi).toContain('getOrCreateCart')
    expect(cartApi).toContain('commerce_carrinho_itens')
    expect(cartApi).toContain('needs_migration')
    expect(checkoutApi).toContain('createVacancyPurchase')
    expect(checkoutApi).toContain('quantity')
    expect(checkoutApi).toContain('forceNew: true')
    expect(checkoutApi).toContain('valor_unitario_centavos')
    expect(wishlistApi).toContain('commerce_favoritos')
    expect(wishlistApi).toContain('.delete()')
    expect(wishlistApi).toContain('.insert({ auth_user_id: user.id')
    expect(wishlistApi).toContain('getBearerUser')

    expect(webList).toContain('/api/me/commerce/cart')
    expect(cartPage).toContain('/api/me/commerce/cart/checkout')
    expect(cartPage).toContain('cpf_cnpj: digits || undefined')
    expect(cartPage).toContain('className="cart-checkout"')
    expect(webList).toContain('/api/me/commerce/wishlist')
    expect(webList).toContain('Authorization: `Bearer ${accessToken}`')
    expect(webList).toContain('commerceItemFromApi')
    expect(webList).toContain('className="directory-market-cart-link"')
    expect(webList).toContain('href="/carrinho"')
    expect(webList).toContain("/?painel=1&perfil=produtora&acao=criar-campeonato")
    expect(webList).toContain('canCreateChampionship')

    expect(appApi).toContain('commerceCart')
    expect(appApi).toContain('addCommerceCart')
    expect(appApi).toContain('checkoutCommerceCartItem')
    expect(appApi).toContain('commerceWishlist')
    expect(appApi).toContain('toggleCommerceWishlist')
    expect(appCommerce).toContain('mobileCommerceFromApi')
    expect(appVacancies).toContain('mobileApi.addCommerceCart')
    expect(appVacancies).toContain('mobileApi.toggleCommerceWishlist')
  })
})
