import { expect, test } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const read = (file: string) => fs.readFileSync(path.join(root, file), 'utf8')

test.describe('Mobile app foundation', () => {
  test('app mantém navegação nativa por perfil e backend compartilhado', async () => {
    const readme = read('app/README.md')
    const pkg = read('app/package.json')
    const entry = read('app/index.ts')
    const env = read('app/src/config/env.ts')
    const api = read('app/src/lib/api.ts')
    const app = read('app/src/App.tsx')
    const types = read('app/src/types/dropzone.ts')
    const auth = read('app/src/lib/auth.tsx')
    const supabase = read('app/src/lib/supabase.ts')
    const secureStorage = read('app/src/lib/secureStorage.ts')
    const home = read('app/src/screens/HomeScreen.tsx')
    const lineup = read('app/src/screens/LineupScreen.tsx')
    const tokenAction = read('app/src/screens/TokenActionScreen.tsx')
    const screens = read('app/src/screens/README.md')

    expect(readme).toContain('mesmo backend, banco, login e regras')
    expect(pkg).toContain('dropzone-mobile')
    expect(pkg).toContain('expo')
    expect(pkg).toContain('"main": "index.ts"')
    expect(entry).toContain('registerRootComponent')

    expect(env).toContain('EXPO_PUBLIC_DROPZONE_API_URL')
    expect(env).toContain('EXPO_PUBLIC_AUTH_REDIRECT_URL')
    expect(env).toContain('dropzone://auth/callback')
    expect(api).toContain('/api/equipe/escalacoes')
    expect(api).toContain('/api/vagas')
    expect(api).toContain('/api/me/carteira')
    expect(api).toContain('/api/lili/chat')

    expect(types).toContain("export type MobileRoute")
    expect(types).toContain("'vacancies'")
    expect(types).toContain("'lineup'")
    expect(types).toContain("'seller_sales'")
    expect(types).toContain("'producer_overview'")
    expect(types).toContain("'commerce'")
    expect(types).toContain("'token_action'")

    expect(app).toContain("useState<MobileRoute>('home')")
    expect(app).toContain('AuthProvider')
    expect(app).toContain('AppErrorBoundary')
    expect(app).toContain('ChampionshipDirectoryScreen')
    expect(app).toContain('LineupScreen')
    expect(app).toContain('TokenActionScreen')
    expect(app).toContain('TeamRosterScreen')
    expect(app).toContain('SellerSalesScreen')
    expect(app).toContain('ProducerOverviewScreen')
    expect(app).toContain('CommerceScreen')
    expect(app).toContain('RankScreen')
    expect(app).toContain('LiliScreen')

    expect(auth).toContain('signInWithOAuth')
    expect(auth).toContain('exchangeCodeForSession')
    expect(auth).toContain('setActiveAccountId')
    expect(supabase).toContain('secureStorage')
    expect(supabase).toContain("flowType: 'pkce'")
    expect(secureStorage).toContain('expo-secure-store')

    expect(home).toContain('mobileApi.vacancies')
    expect(home).toContain('onSelectChampionship')

    expect(lineup).toContain('selectedLineup')
    expect(lineup).toContain('JOGADORES CONFIRMADOS')
    expect(lineup).toContain('Gerar convite de escalação')
    expect(lineup).toContain('Gerar novo convite')
    expect(lineup).toContain('CONVITE ATIVO')
    expect(lineup).toContain('Share.share')
    expect(lineup).toContain('removeLineupPlayer')
    expect(lineup).toContain('revokeLineupInvite')
    expect(lineup).not.toContain('Linking.openURL')
    expect(lineup).not.toContain('WebView')

    expect(tokenAction).toContain("resolvedResult.kind==='lineup'")
    expect(tokenAction).toContain('Este fluxo pode ser concluído diretamente no app.')
    expect(screens).toContain('TeamRosterScreen')
  })
})
