import { expect, test } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const read = (file: string) => fs.readFileSync(path.join(root, file), 'utf8')

test.describe('Mobile app foundation', () => {
  test('app nasce enxuto, por perfil e compartilhando backend', async () => {
    const readme = read('app/README.md')
    const pkg = read('app/package.json')
    const entry = read('app/index.ts')
    const env = read('app/src/config/env.ts')
    const api = read('app/src/lib/api.ts')
    const nav = read('app/src/navigation/mobileExperience.ts')
    const app = read('app/src/App.tsx')
    const errorBoundary = read('app/src/screens/AppErrorBoundary.tsx')
    const eas = read('app/eas.json')
    const auth = read('app/src/lib/auth.tsx')
    const supabase = read('app/src/lib/supabase.ts')
    const secureStorage = read('app/src/lib/secureStorage.ts')
    const login = read('app/src/screens/LoginScreen.tsx')
    const switcher = read('app/src/screens/ProfileSwitcher.tsx')
    const home = read('app/src/screens/HomeScreen.tsx')
    const vacancies = read('app/src/screens/VacanciesScreen.tsx')
    const purchaseClaim = read('app/src/screens/PurchaseClaimScreen.tsx')
    const payments = read('app/src/lib/payments.ts')
    const commerce = read('app/src/lib/commerce.ts')
    const lineup = read('app/src/screens/LineupScreen.tsx')
    const lili = read('app/src/screens/LiliScreen.tsx')
    const wallet = read('app/src/screens/WalletScreen.tsx')
    const commerceScreen = read('app/src/screens/CommerceScreen.tsx')
    const invites = read('app/src/screens/InvitesScreen.tsx')
    const teamRoster = read('app/src/screens/TeamRosterScreen.tsx')
    const sellerSales = read('app/src/screens/SellerSalesScreen.tsx')
    const producerOverview = read('app/src/screens/ProducerOverviewScreen.tsx')
    const rank = read('app/src/screens/RankScreen.tsx')
    const screens = read('app/src/screens/README.md')

    expect(readme).toContain('mesmo backend, banco, login e regras')
    expect(readme).toContain('O que continua no site')
    expect(pkg).toContain('dropzone-mobile')
    expect(pkg).toContain('expo')
    expect(pkg).toContain('"main": "index.ts"')
    expect(entry).toContain('registerRootComponent')
    expect(entry).toContain("./src/App")
    expect(env).toContain('EXPO_PUBLIC_DROPZONE_API_URL')
    expect(env).toContain('EXPO_PUBLIC_AUTH_REDIRECT_URL')
    expect(env).toContain('dropzone://auth/callback')
    expect(env).toContain('externalUrl')
    expect(api).toContain('/api/vagas')
    expect(api).toContain('DEFAULT_TIMEOUT_MS')
    expect(api).toContain('AbortController')
    expect(api).toContain('/api/me/commerce/cart')
    expect(api).toContain('/api/me/commerce/wishlist')
    expect(api).toContain('removeCommerceCartItem')
    expect(api).toContain('updateCommerceCartItem')
    expect(api).toContain('/api/pagamentos/vaga')
    expect(api).toContain('announcements')
    expect(api).toContain('/api/agenda?scope=me')
    expect(api).toContain('/api/equipe/escalacoes')
    expect(api).toContain('/api/me/carteira')
    expect(api).toContain('/api/me/carteira/comprovante/')
    expect(api).toContain('/api/notificacoes?limit=30')
    expect(api).toContain('/api/notificacoes/${encodeURIComponent(id)}/${action}')
    expect(api).toContain('/api/vendedores/${encodeURIComponent(managerId)}/vendas')
    expect(api).toContain('/api/produtora/vendedores')
    expect(api).toContain('/api/rank')
    expect(api).toContain('/api/lili/chat')
    expect(nav).toContain('browse_vacancies')
    expect(nav).toContain('lineup')
    expect(nav).toContain('seller_sales')
    expect(nav).toContain('producer_overview')
    expect(nav).toContain('commerce')
    expect(app).toContain("useState<MobileRoute>('home')")
    expect(app).toContain('AuthProvider')
    expect(app).toContain('AppErrorBoundary')
    expect(errorBoundary).toContain('Voltar para o início')
    expect(app).toContain('LoginScreen')
    expect(app).toContain('onSelectChampionship={screenProps.onSelectChampionship}')
    expect(app).toContain('VacanciesScreen')
    expect(app).toContain('PurchaseClaimScreen')
    expect(app).toContain('LineupScreen')
    expect(app).toContain('InvitesScreen')
    expect(app).toContain('TeamRosterScreen')
    expect(app).toContain('SellerSalesScreen')
    expect(app).toContain('ProducerOverviewScreen')
    expect(app).toContain('CommerceScreen')
    expect(app).toContain('RankScreen')
    expect(app).toContain('LiliScreen')
    expect(eas).toContain('"developmentClient": true')
    expect(eas).toContain('"buildType": "apk"')
    expect(auth).toContain('/api/me')
    expect(auth).toContain('signInWithOAuth')
    expect(auth).toContain('skipBrowserRedirect: true')
    expect(auth).toContain('Linking.openURL')
    expect(auth).toContain('exchangeCodeForSession')
    expect(auth).toContain('authRedirectUrl')
    expect(auth).toContain('setActiveAccountId')
    expect(supabase).toContain('secureStorage')
    expect(supabase).toContain("flowType: 'pkce'")
    expect(secureStorage).toContain('expo-secure-store')
    expect(login).toContain('Entrar com Google')
    expect(login).toContain('EXPO_PUBLIC_SUPABASE_URL')
    expect(login).toContain('Redirect mobile inválido')
    expect(switcher).toContain('Nenhum perfil encontrado')
    expect(switcher).toContain('Criar perfil no site')
    expect(switcher).toContain("apiUrl('/login')")
    expect(home).toContain('O que você precisa resolver agora?')
    expect(home).toContain('Campeonatos com vagas')
    expect(home).toContain('Escalação pendente')
    expect(home).toContain('routeForAction')
    expect(home).toContain('ProfileSwitcher')
    expect(home).toContain('mobileApi.vacancies')
    expect(home).toContain('onSelectChampionship')
    expect(home).toContain('Ver todas as vagas')
    expect(home).toContain('addMobileCart')
    expect(home).toContain('Favoritar')
    expect(home).toContain('Carrinho:')
    expect(vacancies).toContain('Garantir vaga')
    expect(vacancies).toContain('mobileApi.vacancies')
    expect(vacancies).toContain("useState<FilterId>('all')")
    expect(vacancies).toContain('Com live')
    expect(vacancies).toContain('Últimas vagas')
    expect(vacancies).toContain('onSelectChampionship')
    expect(vacancies).toContain('Adicionar ao carrinho')
    expect(vacancies).toContain('toggleMobileWishlist')
    expect(purchaseClaim).toContain('Pagamento seguro')
    expect(purchaseClaim).toContain('Escolher grupo e slot')
    expect(purchaseClaim).toContain('o sistema esquecia o campeonato')
    expect(purchaseClaim).toContain('mobileApi.createVacancyPayment')
    expect(purchaseClaim).toContain('externalUrl(payment.claim_url)')
    expect(purchaseClaim).toContain('Linking.openURL')
    expect(purchaseClaim).toContain('Abrir checkout novamente')
    expect(purchaseClaim).toContain('Abrir inscrição da vaga')
    expect(payments).toContain('PayPal')
    expect(payments).toContain('Cartão')
    expect(commerce).toContain('dropzone:mobile:cart:v1')
    expect(commerce).toContain('dropzone:mobile:wishlist:v1')
    expect(commerce).toContain('AsyncStorage')
    expect(screens).toContain('PurchaseClaimScreen')
    expect(screens).toContain('TeamRosterScreen')
    expect(lineup).toContain('Gerar convite de escalação')
    expect(lineup).toContain('Token ativo')
    expect(lineup).toContain('createdInvite')
    expect(lineup).toContain('Abrir link de escalação')
    expect(lineup).toContain('Linking.openURL')
    expect(lineup).toContain('mobileApi.lineups')
    expect(lineup).toContain('createLineupInvite')
    expect(lineup).toContain('jogador inscrito em outra equipe')
    expect(read('app/src/screens/AgendaScreen.tsx')).toContain('mobileApi.agenda')
    expect(read('app/src/screens/MyChampionshipsScreen.tsx')).toContain('mobileApi.lineups')
    expect(wallet).toContain('mobileApi.wallet')
    expect(wallet).toContain('mobileApi.receipt')
    expect(wallet).toContain('Saldo e comprovantes')
    expect(wallet).toContain('Comprovante')
    expect(commerceScreen).toContain('Carrinho e favoritos')
    expect(commerceScreen).toContain('checkoutCommerceCartItem')
    expect(commerceScreen).toContain('externalUrl(payload.claim_url)')
    expect(commerceScreen).toContain('checkoutByItem')
    expect(commerceScreen).toContain('Abrir checkout')
    expect(commerceScreen).toContain('Abrir inscrição liberada')
    expect(commerceScreen).toContain('removeCommerceCartItem')
    expect(commerceScreen).toContain('updateCommerceCartItem')
    expect(commerceScreen).toContain('quantidade de vagas')
    expect(commerceScreen).toContain('paymentMethods')
    expect(commerceScreen).toContain('PayPal')
    expect(commerceScreen).toContain('Cartão')
    expect(invites).toContain('mobileApi.notifications')
    expect(invites).toContain('respondNotification')
    expect(invites).toContain('Aceitar')
    expect(invites).toContain('Recusar')
    expect(teamRoster).toContain('mobileApi.lineups')
    expect(teamRoster).toContain('Equipe e lines')
    expect(sellerSales).toContain('mobileApi.sellerSales')
    expect(sellerSales).toContain('Vendas de vagas')
    expect(sellerSales).toContain('openSale')
    expect(sellerSales).toContain('externalUrl(target)')
    expect(producerOverview).toContain('mobileApi.producerSellers')
    expect(producerOverview).toContain('Painel rápido')
    expect(rank).toContain('Ranking competitivo')
    expect(rank).toContain('mobileApi.rank')
    expect(rank).toContain('Top equipes')
    expect(rank).toContain('Top jogadores')
    expect(lili).toContain('TextInput')
    expect(lili).toContain('mobileApi.lili')
    expect(lili).toContain('Digite o que precisa resolver')
    expect(lili).toContain('Quero escalar meu elenco')
    expect(lili).toContain('Quero comprar uma vaga')
    expect(screens).toContain('PurchaseClaimScreen')
    expect(screens).toContain('Se uma ação exigir configuração avançada')
  })
})
