import fs from 'node:fs'
import path from 'node:path'
import { expect, test } from '@playwright/test'

const root=path.resolve(__dirname,'../..')
const read=(file:string)=>fs.readFileSync(path.join(root,file),'utf8')

test.describe('Mobile — paridade com os fluxos oficiais do site',()=>{
  test('token guia login, perfil e line disponível usando contratos oficiais',async()=>{
    const app=read('app/src/App.tsx')
    const screen=read('app/src/screens/TokenActionScreen.tsx')
    const parity=read('app/src/lib/profileParity.ts')
    const teamInvite=read('web/app/api/convites/equipe/[token]/route.ts')
    expect(app).toContain("else requireLogin('token_action')")
    expect(screen).toContain('Token reconhecido')
    expect(screen).toContain('Login confirmado')
    expect(screen).toContain('Perfil necessário')
    expect(screen).toContain('quickTokenRequiredProfiles')
    expect(screen).toContain('lines_disponiveis')
    expect(screen).toContain('Somente lines ainda não inscritas neste campeonato')
    expect(screen).toContain('nome_line=newLineName.trim()')
    expect(parity).toContain("return ['equipe', 'manager']")
    expect(parity).toContain("return ['jogador']")
    expect(teamInvite).toContain('lines_disponiveis: livres')
    expect(teamInvite).toContain('lines_inscritas')
  })

  test('cadastro de equipe e perfis replica campos do site sem formulário genérico',async()=>{
    const create=read('app/src/screens/ProfileCreateScreen.tsx')
    const team=read('app/src/screens/TeamCreateScreen.tsx')
    const edit=read('app/src/screens/ProfileManagementScreen.tsx')
    const site=read('web/features/dropzone/DropZoneHome.tsx')
    const register=read('web/app/api/auth/register/route.ts')
    expect(team).toContain('ProfileCreateScreen profileType="equipe"')
    expect(create).toContain("upload_intent:'create_profile'")
    expect(create).toContain('loginSuggestion(form.name)')
    expect(create).toContain('Nome da equipe')
    expect(create).toContain('ID de jogo')
    expect(create).toContain('Nome do manager')
    expect(create).toContain('Nome do broadcast')
    expect(create).toContain('Localização')
    expect(site).toContain('Nome da equipe')
    expect(register).toContain("['support', 'rush', 'sniper', 'bomber']")
    expect(edit).toContain('PLAYER_ROLES.map')
    expect(edit).not.toContain('granadeiro')
    expect(edit).not.toContain('Outra função')
    expect(edit).not.toContain('Bio da produtora')
  })

  test('home e diretório usam cards com vagas abertas, ordem por data, desejo e carrinho',async()=>{
    const home=read('app/src/screens/HomeScreen.tsx')
    const directory=read('app/src/screens/ChampionshipDirectoryScreen.tsx')
    const card=read('app/src/screens/ChampionshipVacancyCard.tsx')
    expect(home).not.toContain('Ações rápidas')
    expect(home).toContain('Number(item.vagas_livres||0)>0')
    expect(home).toContain('dateKey(a).localeCompare(dateKey(b))')
    expect(home).toContain('ChampionshipVacancyCard')
    expect(directory).toContain('Number(item.vagas_livres||0)>0')
    expect(directory).toContain('dateKey(a).localeCompare(dateKey(b))')
    expect(directory).toContain('ChampionshipVacancyCard')
    expect(card).toContain('Lista de desejos')
    expect(card).toContain('Adicionar ao carrinho')
    expect(card).toContain('Vagas livres')
  })
})
