import { test, expect } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const migration = fs.readFileSync(path.join(root, 'database/migrations/20260818_identidade_publica_equipes_lines.sql'), 'utf8')
const provisionalRoute = fs.readFileSync(path.join(root, 'web/app/api/produtora/equipes-provisorias/route.ts'), 'utf8')
const provisionalPanel = fs.readFileSync(path.join(root, 'web/features/produtoras/components/ProvisionalTeamsPanel.tsx'), 'utf8')
const linesRoute = fs.readFileSync(path.join(root, 'web/app/api/equipes/[id]/lines/route.ts'), 'utf8')
const publicSearch = fs.readFileSync(path.join(root, 'web/app/api/equipes/busca-publica/route.ts'), 'utf8')
const championshipSearch = fs.readFileSync(path.join(root, 'web/app/api/campeonatos/[id]/equipes/busca/route.ts'), 'utf8')

test('107 - nome e TAG não são identidade única de equipe ou line', async () => {
  expect(migration).toContain('drop constraint if exists equipes_tag_unique')
  expect(migration).toContain('drop index if exists public.equipe_lines_equipe_nome_unique')
  expect(migration).not.toContain('where lower(trim(nome)) = lower(v_nome)')
  expect(provisionalRoute).not.toContain('const seen = new Set<string>()')
  expect(provisionalPanel).not.toContain('const seen = new Set<string>()')
})

test('107 - equipe e line possuem identidade pública numérica própria', async () => {
  expect(migration).toContain("add column if not exists public_id bigint generated by default as identity")
  expect(migration).toContain("add column if not exists public_id_prefix text default 'LN'")
  expect(migration).toContain('create unique index if not exists equipe_lines_public_id_unique')
  expect(provisionalRoute).toContain('public_id,public_id_prefix')
  expect(linesRoute).toContain('public_id,public_id_prefix')
  expect(provisionalPanel).toContain('EQ${team.public_id}')
  expect(provisionalPanel).toContain('LN${line.public_id}')
})

test('107 - busca aceita ID público sem depender de nome ou TAG', async () => {
  expect(publicSearch).toContain('/^(?:EQ\\s*)?(\\d+)$/i')
  expect(publicSearch).toContain("query.eq('public_id', publicId)")
  expect(championshipSearch).toContain('/^LN\\s*(\\d+)$/i')
  expect(championshipSearch).toContain(".eq('public_id', linePublicId)")
})

test('107 - cadastro em bloco preserva registros repetidos e feedback após recarga', async () => {
  expect(migration).toContain("return jsonb_build_object('criadas', v_criadas)")
  expect(provisionalPanel).toContain('Cada cadastro recebe um ID público próprio')
  expect(provisionalPanel).toContain('await load({ preserveMessage: true })')
})
