import { expect, test } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const read = (file: string) => fs.readFileSync(path.join(root, file), 'utf8')

test.describe('Rodada 88E — pagamento público de vaga', () => {
  test('site expõe meios seguros e preserva retorno para compra de vaga', async () => {
    const modal = read('web/features/billing/BuyVacancyModal.tsx')
    const api = read('web/app/api/pagamentos/vaga/route.ts')
    const paypal = read('backend/src/billing/paypal.ts')
    const purchase = read('backend/src/billing/vacancy-purchase.ts')
    const claimPage = read('web/app/vagas/compra/[token]/page.tsx')
    const liliChat = read('web/app/api/lili/chat/route.ts')
    const liliTools = read('web/features/lili/tools.ts')
    const walletPage = read('web/app/carteira/page.tsx')
    const sellerSalesApi = read('web/app/api/vendedores/[managerId]/vendas/route.ts')
    const sellerChampionshipsApi = read('web/app/api/vendedores/[managerId]/campeonatos/route.ts')
    const sellerPanel = read('web/features/dropzone/panels/manager/ManagerVendasView.tsx')
    const sellerPublicPage = read('web/app/vendedores/[managerId]/page.tsx')
    const css = read('web/app/vagas/vagas.css')

    expect(modal).toContain('Pagar com PIX')
    expect(modal).toContain('Pagar com cart')
    expect(modal).toContain('Pagar com PayPal')
    expect(modal).toContain('method,')
    expect(modal).toContain('paypal_approval_url')

    expect(api).toContain("['pix', 'cartao', 'paypal']")
    expect(api).toContain("referenceType: 'sistema_compras_vaga'")
    expect(api).toContain('/vagas/compra/')
    expect(api).toContain('paypal_approval_url')

    expect(paypal).toContain('returnUrl?: string')
    expect(paypal).toContain('cancelUrl?: string')
    expect(purchase).toContain("billingType: method === 'cartao' ? 'CREDIT_CARD' : 'PIX'")
    expect(purchase).toContain('/vagas/compra/')
    expect(purchase).not.toContain('?asaas=return')
    expect(purchase).not.toContain('PIX e cartão pelo Asaas')

    expect(claimPage).toContain("'approved'")
    expect(claimPage).toContain('purchaseId')
    expect(claimPage).toContain('/api/paypal/orders/')
    expect(claimPage).not.toContain('sem redirecionar para ASAAS')
    expect(claimPage).toContain('Ver comprovante de pagamento')
    expect(claimPage).toContain('/carteira?comprovante=')

    expect(modal).not.toContain('Checkout seguro Asaas')
    expect(modal).not.toContain('O Asaas')
    expect(liliChat).not.toContain('ao Asaas')
    expect(liliChat).not.toContain('Abra o Asaas')
    expect(liliChat).not.toContain('pelo Asaas')
    expect(liliTools).not.toContain('checkout do Asaas')
    expect(liliTools).toContain('Ver comprovante de pagamento')
    expect(liliTools).toContain('/carteira?comprovante=')
    expect(walletPage).toContain("comprovante.tipo === 'pagamento' ? 'Comprovante de pagamento'")
    expect(walletPage).toContain("searchParams.get('comprovante')")

    expect(sellerChampionshipsApi).toContain('pagamento_cartao_ativo')
    expect(sellerChampionshipsApi).toContain('pagamento_paypal_ativo')
    expect(sellerSalesApi).toContain("['pix', 'cartao', 'paypal']")
    expect(sellerSalesApi).toContain('createLiliPayPalOrder')
    expect(sellerSalesApi).toContain('paypal_approval_url')
    expect(sellerSalesApi).not.toContain("method: 'pix'")
    expect(sellerPanel).toContain("setSaleMethod('cartao')")
    expect(sellerPanel).toContain("setSaleMethod('paypal')")
    expect(sellerPanel).toContain('method: saleMethod')
    expect(sellerPanel).toContain("saleMethod !== 'paypal'")
    expect(sellerPublicPage).toContain('Pague online com comissão')

    expect(css).toContain('.vacancy-buy-option-card')
    expect(css).toContain('.vacancy-buy-option-paypal')
  })
})
