-- =============================================================================
-- DROPZONE · Broadcast (Stream) + chaves de campeonato + sessões de live
-- Rode no Supabase SQL Editor. Idempotente.
-- =============================================================================

-- Perfil Broadcast (papéis: stream, narrador, comentarista, apresentador)
create table if not exists public.broadcasts (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  public_id bigint generated by default as identity,
  public_id_prefix text default 'BR',
  username text not null,
  nome text not null,
  email_contato text not null,
  email_verificado boolean not null default false,
  avatar_url text,
  pais text,
  estado text,
  cidade text,
  localidade text,
  status text not null default 'ativo',
  papel text not null default 'stream'
    check (papel in ('stream', 'narrador', 'comentarista', 'apresentador')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists broadcasts_username_idx
  on public.broadcasts (lower(username));

create index if not exists broadcasts_auth_user_idx
  on public.broadcasts (auth_user_id);

-- Chave do campeonato enviada ao Stream
create table if not exists public.campeonato_stream_keys (
  id uuid primary key default gen_random_uuid(),
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  key_token text not null default encode(gen_random_bytes(12), 'hex'),
  label text not null default 'Chave Stream',
  ativo boolean not null default true,
  criado_por uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_campeonato_stream_keys_token
  on public.campeonato_stream_keys (key_token);

create index if not exists idx_campeonato_stream_keys_champ
  on public.campeonato_stream_keys (campeonato_id, ativo, created_at desc);

-- Campeonatos na lista do Stream
create table if not exists public.broadcast_campeonato_links (
  id uuid primary key default gen_random_uuid(),
  broadcast_id uuid not null references public.broadcasts(id) on delete cascade,
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  stream_key_id uuid null references public.campeonato_stream_keys(id) on delete set null,
  display_name text not null,
  created_at timestamptz not null default now(),
  constraint broadcast_campeonato_links_unique unique (broadcast_id, campeonato_id)
);

create index if not exists idx_broadcast_links_broadcast
  on public.broadcast_campeonato_links (broadcast_id, created_at desc);

-- Sessão de live (controlador + OBS)
create table if not exists public.broadcast_live_sessions (
  id uuid primary key default gen_random_uuid(),
  broadcast_id uuid not null references public.broadcasts(id) on delete cascade,
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  nome text not null default 'Live',
  controller_token text not null default encode(gen_random_bytes(18), 'hex'),
  obs_token text not null default encode(gen_random_bytes(18), 'hex'),
  active_overlay_id uuid null references public.campeonato_stream_overlays(id) on delete set null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists idx_broadcast_sessions_controller
  on public.broadcast_live_sessions (controller_token);

create unique index if not exists idx_broadcast_sessions_obs
  on public.broadcast_live_sessions (obs_token);

create index if not exists idx_broadcast_sessions_broadcast
  on public.broadcast_live_sessions (broadcast_id, updated_at desc);

-- Cenas (composição de overlays do campeonato)
create table if not exists public.campeonato_stream_scenes (
  id uuid primary key default gen_random_uuid(),
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  nome text not null default 'Cena',
  overlay_ids jsonb not null default '[]'::jsonb,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_stream_scenes_champ
  on public.campeonato_stream_scenes (campeonato_id, sort_order);

-- RLS service_role
alter table public.broadcasts enable row level security;
alter table public.broadcasts force row level security;
alter table public.campeonato_stream_keys enable row level security;
alter table public.campeonato_stream_keys force row level security;
alter table public.broadcast_campeonato_links enable row level security;
alter table public.broadcast_campeonato_links force row level security;
alter table public.broadcast_live_sessions enable row level security;
alter table public.broadcast_live_sessions force row level security;
alter table public.campeonato_stream_scenes enable row level security;
alter table public.campeonato_stream_scenes force row level security;

do $$
declare
  t text;
begin
  foreach t in array array[
    'broadcasts',
    'campeonato_stream_keys',
    'broadcast_campeonato_links',
    'broadcast_live_sessions',
    'campeonato_stream_scenes'
  ]
  loop
    execute format('drop policy if exists %I on public.%I', t || '_service_all', t);
    execute format(
      'create policy %I on public.%I for all using (
        coalesce(current_setting(''request.jwt.claim.role'', true), current_setting(''role'', true))
          in (''service_role'', ''supabase_admin'', ''postgres'')
      ) with check (
        coalesce(current_setting(''request.jwt.claim.role'', true), current_setting(''role'', true))
          in (''service_role'', ''supabase_admin'', ''postgres'')
      )',
      t || '_service_all', t
    );
    execute format('revoke all on public.%I from anon, authenticated', t);
  end loop;
end $$;

comment on table public.broadcasts is 'Perfil Broadcast: stream, narrador, comentarista, apresentador.';
comment on table public.campeonato_stream_keys is 'Chave que a produtora envia ao Stream para vincular o campeonato.';
comment on table public.broadcast_live_sessions is 'Sessão de live: controller_token (mesa) + obs_token (Browser Source).';
