/**
 * Catálogo de perguntas do Rulebook Builder.
 * Inspirado em estruturas de regulamentos de Free Fire (formato LBFF/FFWS, FFMC, eJIF, Game Space),
 * com textos e fluxos próprios e parametrizados — sem copiar conteúdo oficial da Garena.
 */
import type { RulebookQuestion } from './rulebook.types'

export const RULEBOOK_QUESTIONS: RulebookQuestion[] = [
  // ─── ETAPA 1: Configuração do campeonato ─────────────────────────────
  {
    id: 'formato_evento',
    etapa: 1,
    chapter: 'disposicoes_gerais',
    label: 'O campeonato será Online, Presencial ou Híbrido?',
    help: 'Define quais módulos de estrutura física ou lobby online serão exibidos.',
    type: 'single',
    required: true,
    options: [
      { value: 'online', label: 'Online' },
      { value: 'presencial', label: 'Presencial' },
      { value: 'hibrido', label: 'Híbrido' },
    ],
    defaultByProfile: {
      comunitario: 'online',
      semiprofissional: 'online',
      profissional: 'hibrido',
    },
  },
  {
    id: 'modalidade',
    etapa: 1,
    chapter: 'partidas',
    label: 'Qual a modalidade principal?',
    type: 'single',
    required: true,
    options: [
      { value: 'squad', label: 'Squad (4 jogadores)' },
      { value: 'duo', label: 'Duo' },
      { value: 'solo', label: 'Solo' },
    ],
    defaultByProfile: {
      comunitario: 'squad',
      semiprofissional: 'squad',
      profissional: 'squad',
      personalizado: 'squad',
    },
  },
  {
    id: 'plataforma',
    etapa: 1,
    chapter: 'partidas',
    label: 'Plataforma permitida',
    type: 'multi',
    required: true,
    options: [
      { value: 'mobile', label: 'Mobile (Android/iOS)' },
      { value: 'emulador', label: 'Emulador (PC)' },
      { value: 'ambos', label: 'Mobile e Emulador' },
    ],
    defaultByProfile: {
      comunitario: ['mobile'],
      semiprofissional: ['mobile'],
      profissional: ['mobile'],
    },
  },
  {
    id: 'emulador_proibido',
    etapa: 1,
    chapter: 'partidas',
    module: 'emulador_proibido',
    label: 'Emulador é proibido neste campeonato?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['emulador_proibido'],
    enableWhen: true,
  },
  {
    id: 'possui_transmissao',
    etapa: 1,
    chapter: 'organizacao',
    module: 'transmissao',
    label: 'Existe transmissão oficial?',
    help: 'Vinculado à opção “Tem transmissão ao vivo” do campeonato.',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: false,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['transmissao'],
    enableWhen: true,
  },
  {
    id: 'possui_premiacao',
    etapa: 1,
    chapter: 'premiacao',
    module: 'premiacao',
    label: 'O campeonato possui premiação?',
    help: 'Vinculado à configuração do campeonato. Alterar aqui atualiza o campeonato e vice-versa.',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: false,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['premiacao'],
    enableWhen: true,
  },
  {
    id: 'permite_manager',
    etapa: 1,
    chapter: 'manager',
    module: 'manager',
    label: 'Permite Manager cadastrado na equipe?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['manager'],
    enableWhen: true,
  },
  {
    id: 'permite_coach',
    etapa: 1,
    chapter: 'coach',
    module: 'coach',
    label: 'Permite Coach na equipe?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: false,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['coach'],
    enableWhen: true,
  },
  {
    id: 'permite_reservas',
    etapa: 1,
    chapter: 'equipes',
    module: 'reservas',
    label: 'Permite jogadores reservas no elenco?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['reservas'],
    enableWhen: true,
  },
  {
    id: 'possui_taxa',
    etapa: 1,
    chapter: 'cadastro',
    module: 'taxa_inscricao',
    label: 'Possui taxa de inscrição?',
    help: 'Vinculado ao valor de inscrição do campeonato.',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: false,
      semiprofissional: false,
      profissional: false,
    },
    enablesModules: ['taxa_inscricao', 'reembolso'],
    enableWhen: true,
  },
  {
    id: 'nivel_campeonato',
    etapa: 1,
    chapter: 'disposicoes_gerais',
    label: 'Classificação do campeonato',
    type: 'single',
    required: true,
    options: [
      { value: 'comunitario', label: 'Comunitário' },
      { value: 'oficial_parceiro', label: 'Oficial / Parceiro de produtora' },
      { value: 'circuito', label: 'Circuito / Liga' },
    ],
    defaultByProfile: {
      comunitario: 'comunitario',
      semiprofissional: 'oficial_parceiro',
      profissional: 'circuito',
    },
  },
  {
    id: 'fase_classificatoria',
    etapa: 1,
    chapter: 'partidas',
    module: 'classificatoria',
    label: 'Existe fase classificatória?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['classificatoria'],
    enableWhen: true,
  },
  {
    id: 'fase_eliminatoria',
    etapa: 1,
    chapter: 'partidas',
    module: 'eliminatoria',
    label: 'Existe fase eliminatória / playoffs?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: false,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['eliminatoria'],
    enableWhen: true,
  },
  {
    id: 'final_presencial',
    etapa: 1,
    chapter: 'partidas',
    module: 'final_presencial',
    label: 'A final será presencial?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: false,
      semiprofissional: false,
      profissional: true,
    },
    enablesModules: ['final_presencial', 'presencial'],
    enableWhen: true,
  },
  {
    id: 'usa_discord',
    etapa: 1,
    chapter: 'organizacao',
    module: 'discord',
    label: 'Comunicação oficial via Discord?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['discord'],
    enableWhen: true,
  },
  {
    id: 'exige_check_in',
    etapa: 1,
    chapter: 'check_in',
    module: 'check_in',
    label: 'Exige check-in antes das partidas?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['check_in'],
    enableWhen: true,
  },
  {
    id: 'politica_desconexao',
    etapa: 1,
    chapter: 'desconexoes',
    module: 'desconexoes',
    label: 'Deseja configurar política de desconexões?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['desconexoes'],
    enableWhen: true,
  },
  {
    id: 'permite_remake',
    etapa: 1,
    chapter: 'remakes',
    module: 'remakes',
    label: 'Permite remake de partidas em casos excepcionais?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['remakes'],
    enableWhen: true,
  },
  {
    id: 'limite_idade',
    etapa: 1,
    chapter: 'elegibilidade',
    module: 'idade',
    label: 'Existe limite de idade mínima?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: false,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['idade'],
    enableWhen: true,
  },
  {
    id: 'direitos_imagem',
    etapa: 1,
    chapter: 'direitos_imagem',
    module: 'direitos_imagem',
    label: 'Incluir cláusula de direitos de imagem?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['direitos_imagem'],
    enableWhen: true,
  },
  {
    id: 'permite_recursos',
    etapa: 1,
    chapter: 'recursos',
    module: 'recursos_disciplinares',
    label: 'Participantes têm direito a recurso de decisões disciplinares?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: false,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['recursos_disciplinares'],
    enableWhen: true,
  },
  {
    id: 'permite_atraso',
    etapa: 1,
    chapter: 'partidas',
    module: 'atrasos',
    label: 'Tolerar atraso no lobby?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['atrasos'],
    enableWhen: true,
  },
  {
    id: 'proibe_hack',
    etapa: 1,
    chapter: 'infracoes',
    module: 'hack',
    label: 'Proibir uso de hacks / softwares de vantagem?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
      personalizado: true,
    },
    enablesModules: ['hack'],
    enableWhen: true,
  },
  {
    id: 'proibe_ghosting',
    etapa: 1,
    chapter: 'infracoes',
    module: 'ghosting',
    label: 'Proibir ghosting?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
      personalizado: true,
    },
    enablesModules: ['ghosting'],
    enableWhen: true,
  },
  {
    id: 'proibe_bug_abuse',
    etapa: 1,
    chapter: 'infracoes',
    module: 'bug_abuse',
    label: 'Proibir abuso de bugs?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['bug_abuse'],
    enableWhen: true,
  },

  // ─── ETAPA 2: Regras dos módulos habilitados ─────────────────────────
  {
    id: 'idade_minima',
    etapa: 2,
    chapter: 'elegibilidade',
    module: 'idade',
    label: 'Qual a idade mínima?',
    type: 'number',
    required: true,
    min: 12,
    max: 21,
    unit: 'anos',
    dependsOn: [{ questionId: 'limite_idade', isTrue: true }],
    defaultByProfile: {
      semiprofissional: 14,
      profissional: 16,
    },
  },
  {
    id: 'autorizacao_responsavel',
    etapa: 2,
    chapter: 'elegibilidade',
    module: 'idade',
    label: 'Menores precisam de autorização do responsável?',
    type: 'boolean',
    required: true,
    dependsOn: [{ questionId: 'limite_idade', isTrue: true }],
    defaultByProfile: {
      semiprofissional: true,
      profissional: true,
    },
  },
  {
    id: 'documentos_idade',
    etapa: 2,
    chapter: 'elegibilidade',
    module: 'idade',
    label: 'Quais documentos serão aceitos para comprovação de idade?',
    type: 'multi',
    required: true,
    dependsOn: [{ questionId: 'limite_idade', isTrue: true }],
    options: [
      { value: 'rg', label: 'RG' },
      { value: 'cpf', label: 'CPF' },
      { value: 'passaporte', label: 'Passaporte' },
      { value: 'certidao', label: 'Certidão de nascimento' },
      { value: 'autorizacao', label: 'Autorização assinada do responsável' },
    ],
    defaultByProfile: {
      semiprofissional: ['rg', 'autorizacao'],
      profissional: ['rg', 'cpf', 'autorizacao'],
    },
  },
  {
    id: 'qtd_titulares',
    etapa: 2,
    chapter: 'equipes',
    label: 'Quantidade de titulares por equipe',
    type: 'number',
    required: true,
    min: 1,
    max: 6,
    defaultByProfile: {
      comunitario: 4,
      semiprofissional: 4,
      profissional: 4,
      personalizado: 4,
    },
  },
  {
    id: 'qtd_reservas',
    etapa: 2,
    chapter: 'equipes',
    module: 'reservas',
    label: 'Quantidade máxima de reservas',
    type: 'number',
    required: true,
    min: 1,
    max: 4,
    dependsOn: [{ questionId: 'permite_reservas', isTrue: true }],
    defaultByProfile: {
      comunitario: 1,
      semiprofissional: 2,
      profissional: 2,
    },
  },
  {
    id: 'substituicao_entre_quedas',
    etapa: 2,
    chapter: 'equipes',
    module: 'reservas',
    label: 'Permite substituição de reserva entre quedas da mesma rodada?',
    type: 'boolean',
    required: true,
    dependsOn: [{ questionId: 'permite_reservas', isTrue: true }],
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
    },
  },
  {
    id: 'check_in_minutos',
    etapa: 2,
    chapter: 'check_in',
    module: 'check_in',
    label: 'Antecedência mínima do check-in (minutos antes do horário oficial)',
    type: 'number',
    required: true,
    min: 5,
    max: 60,
    unit: 'min',
    dependsOn: [{ questionId: 'exige_check_in', isTrue: true }],
    defaultByProfile: {
      comunitario: 10,
      semiprofissional: 15,
      profissional: 20,
    },
  },
  {
    id: 'atraso_maximo_minutos',
    etapa: 2,
    chapter: 'partidas',
    module: 'atrasos',
    label: 'Tempo máximo de atraso tolerado (minutos)',
    type: 'number',
    required: true,
    min: 1,
    max: 30,
    unit: 'min',
    dependsOn: [{ questionId: 'permite_atraso', isTrue: true }],
    defaultByProfile: {
      comunitario: 10,
      semiprofissional: 10,
      profissional: 5,
    },
  },
  {
    id: 'canal_convite_sala',
    etapa: 2,
    chapter: 'partidas',
    module: 'lobby',
    label: 'Como o convite da sala personalizada será enviado?',
    type: 'multi',
    required: true,
    dependsOn: [
      {
        questionId: 'formato_evento',
        equalsAny: ['online', 'hibrido'],
      },
    ],
    options: [
      { value: 'discord', label: 'Discord' },
      { value: 'whatsapp', label: 'WhatsApp' },
      { value: 'plataforma', label: 'Pela plataforma DropZone' },
      { value: 'privado', label: 'Mensagem privada ao manager' },
    ],
    defaultByProfile: {
      comunitario: ['discord', 'whatsapp'],
      semiprofissional: ['discord', 'plataforma'],
      profissional: ['discord', 'plataforma'],
    },
  },
  {
    id: 'delay_obrigatorio',
    etapa: 2,
    chapter: 'organizacao',
    module: 'transmissao',
    label: 'Existe delay obrigatório na transmissão oficial?',
    type: 'boolean',
    required: true,
    dependsOn: [{ questionId: 'possui_transmissao', isTrue: true }],
    defaultByProfile: {
      semiprofissional: true,
      profissional: true,
    },
    enablesModules: ['delay_transmissao'],
    enableWhen: true,
  },
  {
    id: 'delay_segundos',
    etapa: 2,
    chapter: 'organizacao',
    module: 'delay_transmissao',
    label: 'Qual o delay obrigatório (segundos)?',
    type: 'number',
    required: true,
    min: 30,
    max: 300,
    unit: 's',
    dependsOn: [{ questionId: 'delay_obrigatorio', isTrue: true }],
    defaultByProfile: {
      semiprofissional: 90,
      profissional: 120,
    },
  },
  {
    id: 'assistir_propria_transmissao',
    etapa: 2,
    chapter: 'organizacao',
    module: 'transmissao',
    label: 'É permitido assistir à própria transmissão durante a partida?',
    type: 'boolean',
    required: true,
    dependsOn: [{ questionId: 'possui_transmissao', isTrue: true }],
    defaultByProfile: {
      semiprofissional: false,
      profissional: false,
    },
  },
  {
    id: 'ping_responsabilidade',
    etapa: 2,
    chapter: 'desconexoes',
    module: 'desconexoes',
    label: 'Quem é responsável pela qualidade da conexão do jogador?',
    type: 'single',
    required: true,
    dependsOn: [{ questionId: 'politica_desconexao', isTrue: true }],
    options: [
      { value: 'jogador', label: 'Exclusivamente o jogador/equipe' },
      { value: 'organizacao_se_fornecida', label: 'Organização apenas se fornecer rede' },
      { value: 'compartilhada', label: 'Compartilhada (casos analisados)' },
    ],
    defaultByProfile: {
      comunitario: 'jogador',
      semiprofissional: 'jogador',
      profissional: 'organizacao_se_fornecida',
    },
  },
  {
    id: 'desconexao_intencional',
    etapa: 2,
    chapter: 'desconexoes',
    module: 'desconexoes',
    label: 'Desconexão intencional é considerada infração?',
    type: 'boolean',
    required: true,
    dependsOn: [{ questionId: 'politica_desconexao', isTrue: true }],
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
    },
  },
  {
    id: 'remake_condicoes',
    etapa: 2,
    chapter: 'remakes',
    module: 'remakes',
    label: 'Em quais condições o remake pode ser considerado?',
    type: 'multi',
    required: true,
    dependsOn: [{ questionId: 'permite_remake', isTrue: true }],
    options: [
      { value: 'servidor', label: 'Falha no servidor do jogo' },
      { value: 'massiva', label: 'Desconexão massiva de vários jogadores' },
      { value: 'bug_grave', label: 'Bug que impede o jogo normalmente' },
      { value: 'erro_org', label: 'Erro operacional da organização' },
      { value: 'criterio_org', label: 'A critério exclusivo da organização' },
    ],
    defaultByProfile: {
      comunitario: ['servidor', 'criterio_org'],
      semiprofissional: ['servidor', 'massiva', 'bug_grave', 'criterio_org'],
      profissional: ['servidor', 'massiva', 'bug_grave', 'erro_org', 'criterio_org'],
    },
  },
  {
    id: 'valor_taxa',
    etapa: 2,
    chapter: 'cadastro',
    module: 'taxa_inscricao',
    label: 'Valor da taxa de inscrição (descreva ou informe o valor)',
    type: 'text',
    required: true,
    dependsOn: [{ questionId: 'possui_taxa', isTrue: true }],
    placeholder: 'Ex.: R$ 50,00 por equipe',
  },
  {
    id: 'politica_reembolso',
    etapa: 2,
    chapter: 'cadastro',
    module: 'reembolso',
    label: 'Política de reembolso da taxa de inscrição',
    type: 'long_text',
    required: true,
    dependsOn: [{ questionId: 'possui_taxa', isTrue: true }],
    placeholder: 'Ex.: Não reembolsável após confirmação da inscrição, salvo cancelamento do evento.',
  },
  {
    id: 'premiacao_total',
    etapa: 2,
    chapter: 'premiacao',
    module: 'premiacao',
    label: 'Valor total da premiação (R$)',
    help: 'Mesmo valor da configuração do campeonato. A divisão é editada abaixo e não pode ultrapassar este total. (Use 0 se for só brinde.)',
    type: 'text',
    required: false,
    dependsOn: [{ questionId: 'possui_premiacao', isTrue: true }],
    placeholder: 'Ex.: 1000.00',
  },
  {
    id: 'divisao_premiacao_json',
    etapa: 2,
    chapter: 'premiacao',
    module: 'premiacao',
    label: 'Divisão da premiação por colocação',
    help: 'Adicione cada colocação com nome e valor. O restante do prêmio é mostrado automaticamente.',
    type: 'long_text',
    required: false,
    dependsOn: [{ questionId: 'possui_premiacao', isTrue: true }],
    placeholder: 'Editor estruturado',
  },
  {
    id: 'descricao_premiacao',
    etapa: 2,
    chapter: 'premiacao',
    module: 'premiacao',
    label: 'Observações extras da premiação (opcional)',
    type: 'long_text',
    required: false,
    dependsOn: [{ questionId: 'possui_premiacao', isTrue: true }],
    placeholder: 'Ex.: pagamento via PIX em até 15 dias, documentos necessários…',
  },
  {
    id: 'prazo_pagamento_premio',
    etapa: 2,
    chapter: 'premiacao',
    module: 'premiacao',
    label: 'Prazo para pagamento da premiação após o fim do evento',
    type: 'text',
    required: true,
    dependsOn: [{ questionId: 'possui_premiacao', isTrue: true }],
    placeholder: 'Ex.: até 30 dias úteis após envio dos documentos',
    defaultByProfile: {
      semiprofissional: 'até 30 dias úteis após a entrega da documentação',
      profissional: 'até 60 dias após a entrega da documentação válida',
    },
  },
  {
    id: 'competencia_julgamento',
    etapa: 2,
    chapter: 'penalidades',
    label: 'Quem julga as infrações?',
    type: 'single',
    required: true,
    options: [
      { value: 'organizacao', label: 'Organização do campeonato' },
      { value: 'comissao', label: 'Comissão disciplinar designada' },
      { value: 'arbitro', label: 'Árbitro / admin de partida' },
      { value: 'misto', label: 'Admin de partida + revisão da organização' },
    ],
    defaultByProfile: {
      comunitario: 'organizacao',
      semiprofissional: 'misto',
      profissional: 'comissao',
    },
  },
  {
    id: 'prazo_recurso',
    etapa: 2,
    chapter: 'recursos',
    module: 'recursos_disciplinares',
    label: 'Prazo para interpor recurso (após ciência da decisão)',
    type: 'text',
    required: true,
    dependsOn: [{ questionId: 'permite_recursos', isTrue: true }],
    placeholder: 'Ex.: 24 horas',
    defaultByProfile: {
      semiprofissional: '24 horas',
      profissional: '24 horas',
    },
  },
  {
    id: 'hack_ferramentas',
    etapa: 2,
    chapter: 'infracoes',
    module: 'hack',
    label: 'Quais ferramentas/meios são explicitamente proibidos?',
    type: 'multi',
    required: true,
    dependsOn: [{ questionId: 'proibe_hack', isTrue: true }],
    options: [
      { value: 'scripts', label: 'Scripts' },
      { value: 'apk_mod', label: 'APK modificado' },
      { value: 'macro', label: 'Macro' },
      { value: 'softwares', label: 'Softwares externos' },
      { value: 'memoria', label: 'Alteração de memória' },
      { value: 'perifericos', label: 'Periféricos que alterem controles do jogo' },
    ],
    defaultByProfile: {
      comunitario: ['scripts', 'apk_mod', 'macro', 'softwares', 'memoria'],
      semiprofissional: ['scripts', 'apk_mod', 'macro', 'softwares', 'memoria', 'perifericos'],
      profissional: ['scripts', 'apk_mod', 'macro', 'softwares', 'memoria', 'perifericos'],
    },
  },
  {
    id: 'ghosting_quem',
    etapa: 2,
    chapter: 'infracoes',
    module: 'ghosting',
    label: 'Quem pode ser responsabilizado por ghosting?',
    type: 'multi',
    required: true,
    dependsOn: [{ questionId: 'proibe_ghosting', isTrue: true }],
    options: [
      { value: 'jogadores', label: 'Jogadores' },
      { value: 'managers', label: 'Managers' },
      { value: 'coach', label: 'Coach' },
      { value: 'espectadores', label: 'Espectadores vinculados à equipe' },
    ],
    defaultByProfile: {
      comunitario: ['jogadores'],
      semiprofissional: ['jogadores', 'managers', 'coach'],
      profissional: ['jogadores', 'managers', 'coach', 'espectadores'],
    },
  },
  {
    id: 'mapas_permitidos',
    etapa: 2,
    chapter: 'partidas',
    label: 'Mapas utilizados no campeonato',
    type: 'multi',
    required: true,
    options: [
      { value: 'bermuda', label: 'Bermuda' },
      { value: 'purgatorio', label: 'Purgatório' },
      { value: 'kalahari', label: 'Kalahari' },
      { value: 'alpine', label: 'Alpine' },
      { value: 'nexterra', label: 'Nexterra' },
    ],
    defaultByProfile: {
      comunitario: ['bermuda', 'purgatorio'],
      semiprofissional: ['bermuda', 'purgatorio', 'kalahari'],
      profissional: ['bermuda', 'purgatorio', 'kalahari', 'alpine'],
    },
  },
  {
    id: 'pontos_kill',
    etapa: 2,
    chapter: 'pontuacao',
    label: 'Pontos por abate (kill)',
    type: 'number',
    required: true,
    min: 0,
    max: 5,
    defaultByProfile: {
      comunitario: 1,
      semiprofissional: 1,
      profissional: 1,
      personalizado: 1,
    },
  },
  {
    id: 'tabela_colocacao',
    etapa: 2,
    chapter: 'pontuacao',
    label: 'Modelo de pontuação por colocação',
    type: 'single',
    required: true,
    options: [
      { value: 'padrao_br', label: 'Padrão BR (1º=12 … kill=1) — a organização detalhará a tabela' },
      { value: 'custom', label: 'Personalizado (detalhar em observações do campeonato)' },
      { value: 'simples', label: 'Simples (1º=10, 2º=8 … + kill)' },
    ],
    defaultByProfile: {
      comunitario: 'simples',
      semiprofissional: 'padrao_br',
      profissional: 'padrao_br',
    },
  },

  // ─── ETAPA 3: campos extras de processo disciplinar (infrações no catálogo próprio) ─
  {
    id: 'prazo_denuncia',
    etapa: 3,
    chapter: 'infracoes',
    label: 'Prazo para denunciar infrações após a partida',
    type: 'text',
    required: true,
    placeholder: 'Ex.: 24 horas',
    defaultByProfile: {
      comunitario: '12 horas',
      semiprofissional: '24 horas',
      profissional: '24 horas',
    },
  },
  {
    id: 'direito_defesa_geral',
    etapa: 3,
    chapter: 'penalidades',
    label: 'Garantir direito de defesa antes de punições graves?',
    type: 'boolean',
    required: true,
    defaultByProfile: {
      comunitario: true,
      semiprofissional: true,
      profissional: true,
    },
  },
]
