begin;

-- ============================================================================
-- Identidade pública de equipes e lines
--
-- Regra de domínio:
--   * nome e TAG NÃO identificam uma equipe/line e podem se repetir;
--   * UUID continua sendo a chave técnica interna;
--   * public_id é a identidade numérica pública usada em busca e suporte;
--   * equipes usam EQ<public_id> e lines usam LN<public_id>.
-- ============================================================================

-- 1) Equipes: remove unicidades antigas de nome/TAG sem tocar em username/auth.
alter table public.equipes drop constraint if exists equipes_tag_unique;
alter table public.equipes drop constraint if exists equipes_nome_unique;
drop index if exists public.equipes_tag_unique;
drop index if exists public.equipes_nome_unique;

-- Garante identidade pública já prevista no modelo de equipes.
alter table public.equipes
  add column if not exists public_id bigint generated by default as identity,
  add column if not exists public_id_prefix text default 'EQ';

update public.equipes
   set public_id_prefix = 'EQ'
 where public_id_prefix is null or trim(public_id_prefix) = '';

create unique index if not exists equipes_public_id_unique
  on public.equipes (public_id)
  where public_id is not null;

-- 2) Lines: nome/TAG também podem se repetir, inclusive dentro da mesma equipe.
drop index if exists public.equipe_lines_equipe_nome_unique;
alter table public.equipe_lines drop constraint if exists equipe_lines_equipe_nome_unique;
alter table public.equipe_lines drop constraint if exists equipe_lines_tag_unique;
drop index if exists public.equipe_lines_tag_unique;

alter table public.equipe_lines
  add column if not exists public_id bigint generated by default as identity,
  add column if not exists public_id_prefix text default 'LN';

update public.equipe_lines
   set public_id = default
 where public_id is null;

update public.equipe_lines
   set public_id_prefix = 'LN'
 where public_id_prefix is null or trim(public_id_prefix) = '';

alter table public.equipe_lines
  alter column public_id set not null,
  alter column public_id_prefix set default 'LN';

create unique index if not exists equipe_lines_public_id_unique
  on public.equipe_lines (public_id);

-- 3) Cadastro provisório: cada linha importada representa uma entidade própria.
--    Não deduplica por nome nem por TAG; o public_id diferencia registros iguais.
create or replace function public.fn_criar_equipes_provisorias_em_bloco(
  p_produtora_id uuid,
  p_criado_por uuid,
  p_equipes jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
declare
  v_item jsonb;
  v_nome text;
  v_tag text;
  v_equipe public.equipes%rowtype;
  v_line_id uuid;
  v_token text;
  v_criadas integer := 0;
begin
  if p_produtora_id is null or p_criado_por is null then
    raise exception 'Produtora e usuário são obrigatórios.';
  end if;
  if p_equipes is null or jsonb_typeof(p_equipes) <> 'array' or jsonb_array_length(p_equipes) = 0 then
    raise exception 'Informe ao menos uma equipe.';
  end if;
  if jsonb_array_length(p_equipes) > 100 then
    raise exception 'O cadastro em bloco aceita no máximo 100 equipes por vez.';
  end if;

  if not exists (
    select 1
      from public.produtoras p
     where p.id = p_produtora_id
       and p.auth_user_id = p_criado_por
       and coalesce(p.status, 'ativo') = 'ativo'
  ) then
    raise exception 'Somente o dono da produtora pode cadastrar equipes provisórias.';
  end if;

  for v_item in select value from jsonb_array_elements(p_equipes)
  loop
    v_nome := regexp_replace(trim(coalesce(v_item->>'nome', '')), '\s+', ' ', 'g');
    if v_nome = '' then
      continue;
    end if;

    v_tag := upper(regexp_replace(trim(coalesce(v_item->>'tag', '')), '[^[:alnum:]]+', '', 'g'));
    if v_tag = '' then
      v_tag := left(upper(regexp_replace(v_nome, '[^[:alnum:]]+', '', 'g')), 5);
    end if;
    if v_tag = '' then
      v_tag := 'TIME';
    end if;

    insert into public.equipes (
      nome, tag, logo_url, auth_user_id, dono_auth_user_id, status
    ) values (
      v_nome, v_tag, null, null, null, 'ativo'
    )
    returning * into v_equipe;

    select id
      into v_line_id
      from public.equipe_lines
     where equipe_id = v_equipe.id
       and coalesce(status, 'ativo') = 'ativo'
     order by created_at asc
     limit 1;

    v_token := replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '');

    insert into public.tokens (
      token, tipo, produtora_id, equipe_id, line_id, criado_por,
      usado, status, expira_em
    ) values (
      v_token, 'reivindicacao_equipe_historica', p_produtora_id, v_equipe.id, v_line_id, p_criado_por,
      false, 'ativo', null
    );

    insert into public.sistema_auditoria(
      administrador_auth_user_id, acao, alvo_tipo, alvo_id, detalhes
    ) values (
      p_criado_por,
      'criar_equipe_provisoria',
      'equipe',
      v_equipe.id::text,
      jsonb_build_object(
        'produtora_id', p_produtora_id,
        'nome', v_nome,
        'tag', v_tag,
        'public_id', v_equipe.public_id,
        'line_id', v_line_id
      )
    );

    v_criadas := v_criadas + 1;
  end loop;

  return jsonb_build_object('criadas', v_criadas);
end;
$$;

revoke all on function public.fn_criar_equipes_provisorias_em_bloco(uuid, uuid, jsonb) from public, anon, authenticated;
grant execute on function public.fn_criar_equipes_provisorias_em_bloco(uuid, uuid, jsonb) to service_role;

commit;

notify pgrst, 'reload schema';
