-- DropZone schema baseline verified against the live Supabase Data API on 2026-07-10.
-- This file intentionally uses the original project tables. It does not create
-- duplicate *_perfis tables.

create extension if not exists pgcrypto;

create or replace function public.dropzone_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.produtoras (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  public_id bigint generated by default as identity,
  public_id_prefix text default 'PD',
  username text not null,
  nome text not null,
  email_contato text not null,
  email_verificado boolean not null default false,
  logo_url text,
  pais text,
  estado text,
  cidade text,
  localidade text,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.equipes (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  tag text not null,
  logo_url text,
  dono_auth_user_id uuid not null references auth.users(id) on delete cascade,
  senha_dono text,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  auth_user_id uuid references auth.users(id) on delete cascade,
  public_id bigint generated by default as identity,
  public_id_prefix text default 'EQ',
  username text,
  email_contato text,
  email_verificado boolean not null default false,
  pais text,
  estado text,
  cidade text,
  localidade text
);

create table if not exists public.jogadores (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  nome text not null,
  email_contato text not null,
  email_verificado boolean not null default false,
  avatar_url text,
  id_jogo text not null,
  funcao text not null,
  pais text,
  estado text,
  cidade text,
  localidade text,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.managers (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  public_id bigint generated by default as identity,
  public_id_prefix text default 'MN',
  username text not null,
  nome text not null,
  email_contato text not null,
  email_verificado boolean not null default false,
  avatar_url text,
  pais text,
  estado text,
  cidade text,
  localidade text,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.campeonatos (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  tipo text not null default 'copa' check (tipo in ('diario', 'copa', 'liga', 'xtreino', 'confronto')),
  logo_url text,
  banner_url text,
  premiacao text,
  divisao_premiacao text,
  regras_url text,
  status text not null default 'ativo',
  criado_por uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.campeonato_fases (
  id uuid primary key default gen_random_uuid(),
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  nome text not null,
  ordem integer not null default 1,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.campeonato_grupos (
  id uuid primary key default gen_random_uuid(),
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  nome text not null,
  slots integer not null default 12,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  fase_id uuid references public.campeonato_fases(id) on delete set null
);

-- Old global uniqueness caused "Grupo A" to fail even when the visible phase was empty.
alter table public.campeonato_grupos drop constraint if exists campeonato_grupos_nome_unique;
drop index if exists public.campeonato_grupos_nome_unique;
drop index if exists public.campeonato_grupos_contexto_nome_idx;
create unique index if not exists campeonato_grupos_contexto_nome_idx
  on public.campeonato_grupos (campeonato_id, coalesce(fase_id, '00000000-0000-0000-0000-000000000000'::uuid), lower(nome));

create table if not exists public.campeonato_equipes (
  id uuid primary key default gen_random_uuid(),
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  equipe_id uuid not null references public.equipes(id) on delete cascade,
  vaga_id uuid,
  grupo_id uuid references public.campeonato_grupos(id) on delete set null,
  line_id uuid,
  slot_numero integer,
  nome_exibicao text,
  origem_entrada text not null default 'organizador',
  criado_por uuid references auth.users(id) on delete set null,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint campeonato_equipes_unique unique (campeonato_id, equipe_id)
);

alter table public.campeonato_equipes drop constraint if exists campeonato_equipes_unique;
create unique index if not exists campeonato_equipes_line_unique
  on public.campeonato_equipes (campeonato_id, line_id)
  where line_id is not null and status = 'ativo';

create table if not exists public.campeonato_slots (
  id uuid primary key default gen_random_uuid(),
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  fase_id uuid references public.campeonato_fases(id) on delete set null,
  grupo_id uuid not null references public.campeonato_grupos(id) on delete cascade,
  equipe_id uuid references public.equipes(id) on delete set null,
  slot_numero integer not null,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint campeonato_slots_unique unique (grupo_id, slot_numero)
);

create table if not exists public.campeonato_jogos (
  id uuid primary key default gen_random_uuid(),
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  nome text not null,
  data_jogo date,
  horario time,
  numero_partidas integer not null default 1,
  mapas text[] not null default '{}',
  grupos_ids uuid[] not null default '{}',
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  fase_id uuid references public.campeonato_fases(id) on delete set null
);

create table if not exists public.campeonato_jogos_grupos (
  id uuid primary key default gen_random_uuid(),
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  jogo_id uuid not null references public.campeonato_jogos(id) on delete cascade,
  grupo_id uuid not null references public.campeonato_grupos(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint campeonato_jogos_grupos_unique unique (jogo_id, grupo_id)
);

create table if not exists public.tokens (
  id uuid primary key default gen_random_uuid(),
  token text not null unique,
  tipo text not null,
  produtora_id uuid references public.produtoras(id) on delete cascade,
  campeonato_id uuid references public.campeonatos(id) on delete cascade,
  fase_id uuid references public.campeonato_fases(id) on delete set null,
  grupo_id uuid references public.campeonato_grupos(id) on delete set null,
  equipe_id uuid references public.equipes(id) on delete cascade,
  jogador_id uuid references public.jogadores(id) on delete cascade,
  manager_id uuid references public.managers(id) on delete cascade,
  jogo_id uuid references public.campeonato_jogos(id) on delete cascade,
  criado_por uuid not null references auth.users(id) on delete cascade,
  usado boolean not null default false,
  usado_em timestamptz,
  expira_em timestamptz,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.equipe_jogadores (
  id uuid primary key default gen_random_uuid(),
  equipe_id uuid not null references public.equipes(id) on delete cascade,
  jogador_auth_user_id uuid not null references auth.users(id) on delete cascade,
  nick text,
  foto_url text,
  id_jogo text,
  funcao text,
  localidade text,
  origem text not null default 'manual',
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists equipe_jogadores_unique_idx
  on public.equipe_jogadores (equipe_id, jogador_auth_user_id);

create table if not exists public.campeonato_jogadores (
  id uuid primary key default gen_random_uuid(),
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  equipe_id uuid not null references public.equipes(id) on delete cascade,
  jogador_id uuid references public.jogadores(id) on delete cascade,
  jogo_id uuid references public.campeonato_jogos(id) on delete set null,
  nick text not null,
  foto_url text,
  id_jogo text not null,
  funcao text not null,
  localidade text,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.campeonato_regras (
  id uuid primary key default gen_random_uuid(),
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  fase_id uuid references public.campeonato_fases(id) on delete set null,
  grupo_id uuid references public.campeonato_grupos(id) on delete cascade,
  vagas_por_equipe integer not null default 6,
  abre_em timestamptz,
  encerra_em timestamptz,
  permite_substituicao boolean not null default false,
  max_substituicoes_por_equipe integer not null default 0,
  substituicao_encerra_em timestamptz,
  bloquear_convites_apos_encerramento boolean not null default true,
  status text not null default 'ativo',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.campeonato_links (
  id uuid primary key default gen_random_uuid(),
  campeonato_id uuid not null references public.campeonatos(id) on delete cascade,
  fase_id uuid references public.campeonato_fases(id) on delete set null,
  grupo_id uuid not null references public.campeonato_grupos(id) on delete cascade,
  token text not null unique,
  tipo text not null default 'inscricao',
  titulo text not null default 'Inscricao de jogadores',
  descricao text,
  metadata jsonb not null default '{}'::jsonb,
  ativo boolean not null default true,
  acompanhamento_publico boolean not null default true,
  criado_por uuid not null references auth.users(id) on delete cascade,
  expira_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists produtoras_username_idx on public.produtoras (lower(username));
create unique index if not exists equipes_username_idx on public.equipes (lower(username)) where username is not null;
create unique index if not exists jogadores_username_idx on public.jogadores (lower(username));
create unique index if not exists managers_username_idx on public.managers (lower(username));
create index if not exists campeonatos_criado_por_idx on public.campeonatos (criado_por);
create index if not exists campeonato_equipes_campeonato_id_idx on public.campeonato_equipes (campeonato_id);
create index if not exists campeonato_equipes_equipe_id_idx on public.campeonato_equipes (equipe_id);
create index if not exists campeonato_jogadores_campeonato_id_idx on public.campeonato_jogadores (campeonato_id);
create index if not exists campeonato_jogadores_equipe_id_idx on public.campeonato_jogadores (equipe_id);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'produtoras',
    'equipes',
    'jogadores',
    'managers',
    'campeonatos',
    'campeonato_fases',
    'campeonato_grupos',
    'campeonato_equipes',
    'campeonato_slots',
    'campeonato_jogos',
    'campeonato_jogos_grupos',
    'tokens',
    'equipe_jogadores',
    'campeonato_jogadores',
    'campeonato_regras',
    'campeonato_links'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop trigger if exists trg_%I_updated_at on public.%I', table_name, table_name);
    execute format('create trigger trg_%I_updated_at before update on public.%I for each row execute function public.dropzone_set_updated_at()', table_name, table_name);
  end loop;
end $$;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant select on all tables in schema public to anon;
