import { useEffect, useMemo, useState } from 'react'
import Ionicons from '@expo/vector-icons/Ionicons'
import { ActivityIndicator, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native'
import { mobileApi, QuickTokenResult, resolveQuickToken } from '@/lib/api'
import { MobileAccount } from '@/lib/auth'
import { useChampionshipCommerce } from '@/lib/useChampionshipCommerce'
import { toChampionshipCard, VacancyApiItem } from '@/lib/vacancies'
import { ChampionshipVacancyCard } from '@/screens/ChampionshipVacancyCard'
import { colors, spacing } from '@/theme/tokens'
import { ChampionshipCard, MobileRoute } from '@/types/dropzone'

const dateKey=(item:VacancyApiItem)=>`${item.proxima_data||'9999-12-31'}T${item.proximo_horario||'23:59'}`
export function HomeScreen(props:{onNavigate:(route:MobileRoute)=>void;accounts?:MobileAccount[];accessToken?:string|null;onSelectChampionship?:(championship:ChampionshipCard)=>void;onCreateChampionship?:()=>void;onTokenResolved?:(result:QuickTokenResult)=>void;requireAuth?:(action?:()=>void)=>boolean}){
  const [vacancies,setVacancies]=useState<VacancyApiItem[]>([]),[loadingVacancies,setLoadingVacancies]=useState(true),[tokenValue,setTokenValue]=useState(''),[tokenLoading,setTokenLoading]=useState(false),[tokenError,setTokenError]=useState('')
  const accounts=props.accounts||[],team=accounts.find(item=>item.profile_type==='equipe'),seller=accounts.find(item=>item.profile_type==='manager'),authenticated=Boolean(props.accessToken)
  const commerce=useChampionshipCommerce(props.requireAuth)
  useEffect(()=>{let mounted=true;mobileApi.vacancies().then(payload=>{if(!mounted)return;setVacancies(((payload.announcements as VacancyApiItem[])||[]).filter(item=>Number(item.vagas_livres||0)>0).sort((a,b)=>dateKey(a).localeCompare(dateKey(b))).slice(0,5))}).catch(()=>mounted&&setVacancies([])).finally(()=>mounted&&setLoadingVacancies(false));return()=>{mounted=false}},[])
  const privateActions=useMemo(()=>authenticated?[{icon:'shield-checkmark-outline' as const,title:team?'Minha equipe':'Criar equipe',route:team?'team_roster' as MobileRoute:'team_create' as MobileRoute},{icon:'people-outline' as const,title:'Escalação',route:'lineup' as MobileRoute},{icon:'wallet-outline' as const,title:'Carteira',route:'wallet' as MobileRoute},seller?{icon:'cash-outline' as const,title:'Vendas',route:'seller_sales' as MobileRoute}:{icon:'notifications-outline' as const,title:'Convites',route:'invites' as MobileRoute}]:[],[authenticated,seller,team])
  async function submitToken(){if(!tokenValue.trim()||tokenLoading)return;setTokenLoading(true);setTokenError('');try{const result=await resolveQuickToken(tokenValue,props.accessToken);props.onTokenResolved?.(result);setTokenValue(result.token)}catch(error:any){setTokenError(error?.message||'Token não reconhecido.')}finally{setTokenLoading(false)}}
  return <ScrollView style={styles.page} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">
    <View style={styles.intro}><Text style={styles.kicker}>DROPZONE COMPETITIVE</Text><Text style={styles.title}>Entre no competitivo</Text><Text style={styles.subtitle}>Vagas abertas, acesso por token e sua área competitiva.</Text><View style={styles.heroActions}><TouchableOpacity style={styles.primary} onPress={()=>props.onNavigate('vacancies')}><Ionicons name="ticket-outline" size={23} color="#fff"/><View style={{flex:1}}><Text style={styles.primaryTitle}>Encontrar vaga</Text><Text style={styles.primaryMeta}>Mais próximas primeiro</Text></View><Ionicons name="arrow-forward" size={19} color="#fff"/></TouchableOpacity><TouchableOpacity style={styles.secondary} onPress={()=>props.onCreateChampionship?.()}><Ionicons name="add-circle-outline" size={22} color="#dce2e8"/><Text style={styles.secondaryText}>Criar campeonato</Text></TouchableOpacity></View></View>
    <View style={styles.tokenSection}><View style={styles.tokenHead}><Ionicons name="key-outline" size={20} color={colors.brand}/><View><Text style={styles.sectionKicker}>ACESSO POR TOKEN</Text><Text style={styles.sectionTitle}>Convite ou inscrição guiada</Text></View></View><Text style={styles.tokenDescription}>Cole o token ou link. O app reconhece o tipo, confirma login e perfil necessário e guia a inscrição.</Text><View style={styles.tokenRow}><TextInput value={tokenValue} onChangeText={value=>{setTokenValue(value);setTokenError('')}} placeholder="Token ou link completo" placeholderTextColor="#8b8b87" style={styles.tokenInput} autoCapitalize="characters" autoCorrect={false} onSubmitEditing={()=>void submitToken()}/><TouchableOpacity style={styles.tokenButton} onPress={()=>void submitToken()} disabled={tokenLoading||!tokenValue.trim()}>{tokenLoading?<ActivityIndicator color="#fff"/>:<Ionicons name="arrow-forward" size={21} color="#fff"/>}</TouchableOpacity></View>{tokenError?<Text style={styles.error}>{tokenError}</Text>:null}</View>
    {authenticated&&privateActions.length?<View style={styles.privateSection}><View style={styles.sectionHead}><Text style={styles.sectionKicker}>MINHA ÁREA</Text><TouchableOpacity onPress={()=>props.onNavigate('dashboard')}><Text style={styles.link}>Abrir painel ›</Text></TouchableOpacity></View><View style={styles.privateRow}>{privateActions.map(item=><TouchableOpacity key={item.title} style={styles.privateItem} onPress={()=>props.onNavigate(item.route)}><Ionicons name={item.icon} size={20} color={colors.ink}/><Text style={styles.privateText}>{item.title}</Text></TouchableOpacity>)}</View></View>:null}
    <View style={styles.vacancySection}><View style={[styles.sectionHead,styles.vacancyHead]}><View><Text style={styles.sectionKicker}>VAGAS ABERTAS</Text><Text style={styles.sectionTitle}>Próximos campeonatos</Text></View><TouchableOpacity onPress={()=>props.onNavigate('vacancies')}><Text style={styles.link}>Ver todos ›</Text></TouchableOpacity></View>{loadingVacancies?<View style={styles.loading}><ActivityIndicator color={colors.brand}/><Text style={styles.muted}>Buscando vagas...</Text></View>:null}{!loadingVacancies&&!vacancies.length?<Text style={styles.empty}>Nenhuma vaga aberta agora.</Text>:null}<View style={styles.cards}>{vacancies.map(item=>{const id=String(item.id||'');return <ChampionshipVacancyCard key={id||item.nome} item={item} favorite={commerce.wishlistIds.has(id)} inCart={commerce.cartIds.has(id)} onOpen={()=>props.onSelectChampionship?.(toChampionshipCard(item))} onWishlist={()=>commerce.toggleWishlist(id)} onCart={()=>commerce.addCart(id)}/>})}</View></View>
  </ScrollView>
}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background},content:{paddingBottom:spacing.xxl},intro:{padding:spacing.md,paddingBottom:14,backgroundColor:colors.brandDark},kicker:{color:colors.brand,fontSize:8,fontWeight:'900',letterSpacing:1.7},title:{marginTop:5,color:'#fff',fontSize:28,fontWeight:'900',textTransform:'uppercase'},subtitle:{marginTop:6,color:'#b9c0ca',fontSize:11,lineHeight:16},heroActions:{marginTop:14,gap:7},primary:{minHeight:58,flexDirection:'row',alignItems:'center',gap:10,paddingHorizontal:13,backgroundColor:colors.brand},primaryTitle:{color:'#fff',fontSize:12,fontWeight:'900',textTransform:'uppercase'},primaryMeta:{marginTop:2,color:'rgba(255,255,255,.75)',fontSize:8},secondary:{minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7,borderWidth:1,borderColor:'#475363'},secondaryText:{color:'#dce2e8',fontSize:9,fontWeight:'900',textTransform:'uppercase'},tokenSection:{margin:spacing.md,marginBottom:0,padding:13,backgroundColor:'#fff',borderWidth:1,borderColor:colors.line},tokenHead:{flexDirection:'row',alignItems:'center',gap:8},sectionKicker:{color:colors.brand,fontSize:8,fontWeight:'900',letterSpacing:1.2},sectionTitle:{marginTop:2,color:colors.ink,fontSize:15,fontWeight:'900',textTransform:'uppercase'},tokenDescription:{marginTop:8,color:colors.muted,fontSize:9,lineHeight:14},tokenRow:{marginTop:9,flexDirection:'row'},tokenInput:{flex:1,minHeight:44,paddingHorizontal:10,color:colors.ink,backgroundColor:'#f2eee7',borderWidth:1,borderColor:colors.line,fontSize:10,fontWeight:'800'},tokenButton:{width:48,alignItems:'center',justifyContent:'center',backgroundColor:colors.brand},error:{marginTop:7,color:'#9a3412',fontSize:9,fontWeight:'800'},privateSection:{margin:spacing.md,marginBottom:0},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:8},link:{color:colors.brand,fontSize:9,fontWeight:'900'},privateRow:{flexDirection:'row',gap:6},privateItem:{flex:1,minWidth:0,alignItems:'center',gap:5,paddingVertical:10,backgroundColor:'#e9e3d9'},privateText:{color:colors.ink,fontSize:7,fontWeight:'900',textTransform:'uppercase'},vacancySection:{marginTop:18},vacancyHead:{marginHorizontal:spacing.md},cards:{marginHorizontal:spacing.md,gap:12},loading:{minHeight:55,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},muted:{color:colors.muted,fontSize:10},empty:{marginHorizontal:spacing.md,padding:12,color:colors.muted,backgroundColor:'#e9e3d9',textAlign:'center',fontSize:10,fontWeight:'800'}})
