begin;

-- ID numérico permanente das Lines. O UUID continua como chave técnica;
-- public_id é a referência curta para CSV e nomes de logos das overlays.
alter table public.equipe_lines
  add column if not exists public_id bigint generated by default as identity,
  add column if not exists public_id_prefix text default 'LN';

update public.equipe_lines
   set public_id = default
 where public_id is null;

update public.equipe_lines
   set public_id_prefix = 'LN'
 where public_id_prefix is null or trim(public_id_prefix) = '';

alter table public.equipe_lines
  alter column public_id set not null,
  alter column public_id_prefix set default 'LN';

create unique index if not exists equipe_lines_public_id_unique
  on public.equipe_lines (public_id);

commit;

notify pgrst, 'reload schema';
